### PR TITLE
[feat] - modify to works with typescript/devserver

### PR DESCRIPTION
**Pull request by PooLP**

### CODE REVIEW

**Comment by IamMrandrew** [comment]
@PooLP Wow!! You are turning Loopa with webpack and react packages project?🚀🚀

I checked out the pr branch on my local and test it. However, I have to delete the `.yarnrc.yml` to make it work. Is there to specific yarn path? Is it ok for me to remove the file?

Also, there is some error for the `typescript`:

```
error TS5055: Cannot write file '/home/andrewliyanlap000824/GitHub/loopa/src/assets/js/recorderWorker.js' because it would overwrite input file.

error TS5055: Cannot write file '/home/andrewliyanlap000824/GitHub/loopa/src/recorderWorker.js' because it would overwrite input file.


Found 2 errors.
```

It doesn't affect the build for now, but wondering if you can fix it. 

Thanks for your interest and contribution to the project. 🙌🙌

**Comment by PooLP** [comment]
Hi, 

for context, i needed a exemple to learn tone.js and your project is interesting, but i needed to launch project on local. I had a side project with react/ts, i used this to update your project.

I use a latest Yarn and i had a problem with recoderWorker.js, the es6 import do not work correctly, that's why I added it manually.

It's not perfect and your project deserves an update, but it's a good project for learning. 

If i have a time I will try to make additional modifications (React for front, reel use of typescript, alternative for recorder.js ...)

I don't have a problem with TS (no error/warnig), but i'am on Windows, so it may have difference with linux / macOs, i'm not sure.

**Comment by IamMrandrew** [comment]
> Hi,
> 
> for context, i needed a exemple to learn tone.js and your project is interesting, but i needed to launch project on local. I had a side project with react/ts, i used this to update your project.
> 
> I use a latest Yarn and i had a problem with recoderWorker.js, the es6 import do not work correctly, that's why I added it manually.
> 
> It's not perfect and your project deserves an update, but it's a good project for learning.
> 
> If i have a time I will try to make additional modifications (React for front, reel use of typescript, alternative for recorder.js ...)
> 
> I don't have a problem with TS (no error/warnig), but i'am on Windows, so it may have difference with linux / macOs, i'm not sure.

I see. Yes, the project definitely deserves an update with declarative framework for better readability and maintainability. I use react/typescript in my latest project as well.

I reckon that you can specific the `yarn` version on your local if it doesn't work for you. I will merge the pr without the `yarnrc.yml` 😆.

**Review by IamMrandrew — APPROVED** [review]
LGTM 🚀

**Comment by IamMrandrew** [comment]
@PooLP Something goes wrong on deployment. It stuck after the compiling. Is there any problem with the dependencies or version? Will publish back the original version for now.

No plan to fix it for now.

**Comment by IamMrandrew** [comment]
@PooLP Updated: It works after I disable the analyzer, which causing the deployment timeout on Netlify/ Vercel.

**Comment by PooLP** [comment]
@IamMrandrew, ok i didn't never used this platform.

**Pull request merged**
